package api

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/pyaethu-aung/image-server/internal/api/gen"
	"github.com/pyaethu-aung/image-server/internal/db"
	"github.com/pyaethu-aung/image-server/internal/imageproc"
	"github.com/pyaethu-aung/image-server/internal/storage"
)

// GetImage implements GET /v1/images/{id}. Without transform params it serves
// the stored original; with params it serves a derivative rendered on the fly.
// The generated params are ignored in favour of re-parsing the raw query, so
// imageproc.ParseTransform stays the single source of validation truth.
func (s *Server) GetImage(w http.ResponseWriter, r *http.Request, id gen.ImageID, _ gen.GetImageParams) {
	img, err := s.images.GetImage(r.Context(), id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			writeError(w, http.StatusNotFound, "not_found", "image not found")
			return
		}
		internalError("get image", err).write(w)
		return
	}

	t, err := imageproc.ParseTransform(r.URL.Query())
	if err != nil {
		var pe *imageproc.ParamError
		if errors.As(err, &pe) {
			writeError(w, http.StatusBadRequest, "bad_request", pe.Error())
			return
		}
		internalError("parse transform", err).write(w)
		return
	}

	if t.IsIdentity() {
		s.serveOriginal(w, r, img)
		return
	}
	s.serveTransformed(w, r, img, t)
}

// GetImageMeta implements GET /v1/images/{id}/meta.
func (s *Server) GetImageMeta(w http.ResponseWriter, r *http.Request, id gen.ImageID) {
	img, err := s.images.GetImage(r.Context(), id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			writeError(w, http.StatusNotFound, "not_found", "image not found")
			return
		}
		internalError("get image meta", err).write(w)
		return
	}
	// Metadata may change (a future re-tag), so it is not cached like bytes.
	w.Header().Set("Cache-Control", "no-cache")
	writeJSON(w, http.StatusOK, toAPIImage(img))
}

// serveOriginal streams the stored original bytes back unchanged.
func (s *Server) serveOriginal(w http.ResponseWriter, r *http.Request, img db.Image) {
	rc, err := s.store.Get(r.Context(), img.StorageKey)
	if err != nil {
		// The DB row exists but the object does not: a storage/DB inconsistency,
		// which is a server-side fault rather than client input.
		internalError("get original", err).write(w)
		return
	}
	defer func() { _ = rc.Close() }()

	w.Header().Set("Content-Type", img.MimeType)
	s.setImageCacheControl(w)
	w.WriteHeader(http.StatusOK)
	if _, err := io.Copy(w, rc); err != nil {
		// The status and headers are already committed, so this can only be
		// logged, not turned into an error response.
		slog.Error("serve original", "err", err, "id", img.ID)
	}
}

// derivExt is the file extension for a derivative's storage key: the
// requested output format, or the source type when the format is unset.
func derivExt(img db.Image, t imageproc.Transform) string {
	if t.Format != "" {
		return string(t.Format)
	}
	return strings.TrimPrefix(img.MimeType, "image/")
}

// serveTransformed serves the derivative for img + t, generating it at most
// once. Storage is authoritative for what exists; Redis only remembers it,
// so every Redis failure or stale marker degrades to a storage check or a
// regeneration, never an error response.
func (s *Server) serveTransformed(w http.ResponseWriter, r *http.Request, img db.Image, t imageproc.Transform) {
	ctx := r.Context()
	ck := imageproc.CacheKey(img.ID, t)
	derivKey := "derivatives/" + img.ID.String() + "/" + ck + "." + derivExt(img, t)
	contentType := img.MimeType
	if t.Format != "" {
		contentType = t.Format.ContentType()
	}

	// Fast path: Redis remembers the derivative. A stale marker (object gone
	// from storage) falls through to regeneration.
	if s.cacheHas(ctx, img.ID, ck) {
		if done := s.serveDerivative(ctx, w, derivKey, contentType, img.ID); done {
			return
		}
	} else if exists, err := s.store.Exists(ctx, derivKey); err == nil && exists {
		// Redis forgot (eviction, restart, TTL) but the object survives:
		// repair the marker and serve from storage without regenerating.
		s.cacheRemember(ctx, img.ID, ck)
		if done := s.serveDerivative(ctx, w, derivKey, contentType, img.ID); done {
			return
		}
	} else if err != nil {
		slog.Error("derivative existence check failed", "err", err, "id", img.ID)
	}

	// True miss: generate, persist, remember, serve.
	rc, err := s.store.Get(ctx, img.StorageKey)
	if err != nil {
		internalError("get original", err).write(w)
		return
	}
	src, err := io.ReadAll(rc)
	_ = rc.Close()
	if err != nil {
		internalError("read original", err).write(w)
		return
	}
	out, _, err := imageproc.Apply(src, t, s.cfg.MaxPixels)
	if err != nil {
		internalError("apply transform", err).write(w)
		return
	}
	if err := s.store.Put(ctx, derivKey, bytes.NewReader(out), contentType); err != nil {
		// The response still carries the generated bytes; the next request
		// simply regenerates. Do not remember a derivative that isn't stored.
		slog.Error("store derivative failed", "err", err, "id", img.ID)
	} else {
		s.cacheRemember(ctx, img.ID, ck)
	}

	w.Header().Set("Content-Type", contentType)
	s.setImageCacheControl(w)
	w.WriteHeader(http.StatusOK)
	// out is libvips-encoded image bytes served with an explicit image/*
	// Content-Type and X-Content-Type-Options: nosniff, so it cannot be
	// interpreted as an active document.
	if _, err := w.Write(out); err != nil { //nolint:gosec // G705: image bytes, not HTML; served nosniff with an image/* type
		slog.Error("serve transformed", "err", err, "id", img.ID)
	}
}

// serveDerivative streams a stored derivative. It reports true when the
// response has been written (success, or an error already sent) and false
// when the object is missing and the caller should regenerate.
func (s *Server) serveDerivative(ctx context.Context, w http.ResponseWriter, derivKey, contentType string, id uuid.UUID) bool {
	rc, err := s.store.Get(ctx, derivKey)
	if errors.Is(err, storage.ErrNotFound) {
		return false
	}
	if err != nil {
		internalError("get derivative", err).write(w)
		return true
	}
	defer func() { _ = rc.Close() }()

	w.Header().Set("Content-Type", contentType)
	s.setImageCacheControl(w)
	w.WriteHeader(http.StatusOK)
	if _, err := io.Copy(w, rc); err != nil {
		slog.Error("serve derivative", "err", err, "id", id)
	}
	return true
}

// DeleteImage implements DELETE /v1/images/{id}. The DB row goes first and
// atomically (DELETE ... RETURNING); everything after is best-effort cleanup,
// so a crash mid-purge can leave orphaned objects but never a live record
// pointing at deleted bytes. Storage.List is the authority on derivatives —
// the Redis set may have been evicted.
func (s *Server) DeleteImage(w http.ResponseWriter, r *http.Request, id gen.ImageID) {
	ctx := r.Context()
	img, err := s.images.DeleteImage(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			writeError(w, http.StatusNotFound, "not_found", "image not found")
			return
		}
		internalError("delete image", err).write(w)
		return
	}

	// The record is gone, so the image is gone from the API regardless of
	// how cleanup fares: log failures and still return 204.
	if err := s.store.Delete(ctx, img.StorageKey); err != nil {
		slog.Error("delete original failed", "err", err, "id", id)
	}
	keys, err := s.store.List(ctx, "derivatives/"+id.String()+"/")
	if err != nil {
		slog.Error("list derivatives failed", "err", err, "id", id)
	}
	for _, key := range keys {
		if err := s.store.Delete(ctx, key); err != nil {
			slog.Error("delete derivative failed", "err", err, "id", id, "key", key)
		}
	}
	s.cachePurge(ctx, id)
	w.WriteHeader(http.StatusNoContent)
}

// setImageCacheControl sets the caching policy for served image bytes and
// prevents content-type sniffing. Each URL (id + exact params) maps to
// immutable content, so it can be cached hard.
func (s *Server) setImageCacheControl(w http.ResponseWriter) {
	w.Header().Set("Cache-Control", fmt.Sprintf("public, max-age=%d, immutable", s.cfg.CacheControlMaxAge))
	w.Header().Set("X-Content-Type-Options", "nosniff")
}
