// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: images.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
    original_filename, content_hash, mime_type,
    width, height, size_bytes, storage_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, original_filename, content_hash, mime_type, width, height, size_bytes, storage_key, created_at
`

type CreateImageParams struct {
	OriginalFilename string `json:"original_filename"`
	ContentHash      string `json:"content_hash"`
	MimeType         string `json:"mime_type"`
	Width            int32  `json:"width"`
	Height           int32  `json:"height"`
	SizeBytes        int64  `json:"size_bytes"`
	StorageKey       string `json:"storage_key"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.OriginalFilename,
		arg.ContentHash,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentHash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :one
DELETE FROM images
WHERE id = $1
RETURNING id, original_filename, content_hash, mime_type, width, height, size_bytes, storage_key, created_at
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, deleteImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentHash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, original_filename, content_hash, mime_type, width, height, size_bytes, storage_key, created_at FROM images
WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentHash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getImageByContentHash = `-- name: GetImageByContentHash :one
SELECT id, original_filename, content_hash, mime_type, width, height, size_bytes, storage_key, created_at FROM images
WHERE content_hash = $1
`

func (q *Queries) GetImageByContentHash(ctx context.Context, contentHash string) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByContentHash, contentHash)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentHash,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}
