// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID               uuid.UUID          `json:"id"`
	OriginalFilename string             `json:"original_filename"`
	ContentHash      string             `json:"content_hash"`
	MimeType         string             `json:"mime_type"`
	Width            int32              `json:"width"`
	Height           int32              `json:"height"`
	SizeBytes        int64              `json:"size_bytes"`
	StorageKey       string             `json:"storage_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
